application: epalitipitaka
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: common/app/img/favicon.ico
  upload: common/app/img/favicon\.ico

- url: /google147e4ebe06d05f82\.html
  static_files: app/google147e4ebe06d05f82.html
  upload: app/google147e4ebe06d05f82\.html

- url: /BingSiteAuth\.xml
  static_files: app/BingSiteAuth.xml
  upload: app/BingSiteAuth\.xml

- url: /js/tipitaka\.js
  static_files: app/all_compiled.js
  upload: app/all_compiled\.js

- url: /js
  static_dir: app/js

- url: /common/js
  static_dir: common/app/js

- url: /common/lib
  static_dir: common/app/lib

- url: /romn
  static_dir: common/romn
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /translation
  static_dir: common/translation
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /robots\.txt
  script: serviceweb.app

- url: /json/.+
  script: serviceweb.app

- url: /html/.+
  script: serviceweb.app

#- url: /customRemoteBlobstoreAPI
#  script: customRemoteBlobstoreAPI.app
#  login: admin

- url: /.*
  script: mainweb.app

#builtins:
#- remote_api: on

libraries:
- name: jinja2
  version: latest

- name: lxml
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?common/pytools/.*
- ^(.*/)?common/web\.py/.*
- ^(.*/)?gaelibs/setTranslationData\.py
- ^(.*/)?gaelibs/translation/.*README.md
