application: palidictionary
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /google147e4ebe06d05f82\.html
  static_files: app/google147e4ebe06d05f82.html
  upload: app/google147e4ebe06d05f82\.html

- url: /BingSiteAuth\.xml
  static_files: app/BingSiteAuth.xml
  upload: app/BingSiteAuth\.xml

- url: /robots\.txt
  static_files: common/gae/robots.txt
  upload: common/gae/robots\.txt

- url: /favicon\.ico
  static_files: common/app/img/favicon.ico
  upload: common/app/img/favicon\.ico

- url: /js/palidic\.js
  static_files: app/all_compiled.js
  upload: app/all_compiled\.js

- url: /js
  static_dir: app/js

- url: /common/js
  static_dir: common/app/js

- url: /css
  static_dir: app/css

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

